name: Run TypeScript

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository under $GITHUB_WORKSPACE, so the job can access it
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Run
      run: npm start
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Delete generated .js before committing
      run: find . -type f -name "*.js" -delete

    - name: Commit to the repo
      run: |
        git config --global user.name "eznavy/gh-rewards"
        git config --global user.email "gh-rewards[bot]@eznavy.github.io"
        git add .
        # Force the build to succeed, even if no files were changed
        git commit -m 'Update generated files' || true
        git push